language: node_js
node_js:
  - lts/*
  on:
    branch: docs
install:
  - yarn install # npm ci
  on:
    branch: docs
script:
  - yarn docs:build # npm run docs:build
  on:
    branch: docs
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/.vitepress/dist
  github_token: $GH_PAGES_CI
  keep_history: true
  on:
    branch: docs
