name: CI

env:
  SERVER: production

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "lts/*"
          cache: "npm"
      - run: yarn
      - run: yarn docs:build
      - name: deploy
        run: |
          ls -al
          git init
          git config --global user.email "270680516@q.com"
          git config --global user.name "11os"
          git add -A
          git commit -m 'deploy'
          git push -f https://${{ secrets.GH_PAGES_CI }}@github.com/11os/11os.github.io.git gh-pages
        working-directory: docs/.vitepress/dist
