name: CI

env:
  SERVER: production

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "lts/*"
          cache: "npm"
      - run: yarn
      - run: yarn docs:build
      - run: cd docs/.vitepress/dist
      - run: ls -al
      - run: git init
      - run: git config --global user.email "270680516@q.com"
      - run: git config --global user.name "11os"
      - run: git add -A
      - run: git commit -m 'deploy'
      - run: git push -f https://${{ secrets.GH_PAGES_CI }}@github.com/11os/11os.github.io.git gh-pages
