name: CI

env:
  SERVER: production

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: init node.js
        uses: actions/setup-node@v2
        with:
          node-version: "lts/*"
          cache: "npm"
      - name: build
        run: |
          yarn
          yarn docs:build
      - name: deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: docs/.vitepress/dist
