name: CI

env:
  SERVER: production

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: init gh-pages
        run: |
          git clone -b gh-pages https://${{ secrets.GH_PAGES_CI }}@github.com/11os/11os.github.io.git
        working-directory: docs/.vitepress/dist
      - uses: actions/setup-node@v2
        with:
          node-version: "lts/*"
          cache: "npm"
      - run: yarn
      - run: yarn docs:build
      - name: deploy gh-pages
        run: |
          ls -al
          git add -A
          git commit -m 'deploy'
          git push -f
        working-directory: docs/.vitepress/dist
